# Generated by Django 4.0.4 on 2022-05-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create',
            old_name='name',
            new_name='username',
        ),
    ]
